### ISSUE TITLE
Where is cucutags?

### ISSUE THREAD

**Issue by bitterjug** [rooprob/vim-behave#1]
Hi Robert
[Cucutags at gitorious](https://gitorious.org/cucutags/cucutags/) seems to have gone.
Do you have a copy?

Mark

**Comment by rooprob** [comment]
Hi. Thanks for you message.

Does installing from pip work for you ?

$ pip install cucutags
Collecting cucutags
  Using cached cucutags-0.7.2.tar.gz
Installing collected packages: cucutags
  Running setup.py install for cucutags
Successfully installed cucutags-0.7.2

**Comment by bitterjug** [comment]
Yeah, that works. Thanks!
Is it still maintained, do you know?

**Comment by mcepl** [comment]
cucutags are on https://gitlab.com/mcepl/cucutags and yes, it is maintained.
